"""Artist routing and risk classification module."""

from __future__ import annotations

import logging
import re
from typing import Any

from langchain_core.messages import HumanMessage, SystemMessage
from langchain_core.output_parsers import JsonOutputParser
from langchain_openai import ChatOpenAI
from pydantic import BaseModel, ConfigDict, Field

from .llm import get_chat_model
from .prompts import ROUTING_SYSTEM_PROMPT, build_routing_human_prompt
from .reply import ConversationReplyComposer
from .schemas import (
    AIExtractionOutput,
    ConfidenceLevel,
    Message,
    RiskLevel,
    SuggestedArtist,
    TattooExtractionDraft,
)

LOGGER = logging.getLogger(__name__)

_NINA_STYLE_TAGS = {"fine-line", "minimal", "micro-realism"}
_HOSS_STYLE_TAGS = {"watercolor", "traditional"}
_ALL_STANDARD_INTAKE_MISSING = {
    "size in cm",
    "placement",
    "reference images",
    "color preference",
    "preferred date",
}

_HIGH_RISK_TERMS = (
    "price",
    "pricing",
    "cost",
    "quote",
    "booking",
    "book an appointment",
    "complaint",
    "refund",
    "bad experience",
    "design this for me",
    "complex design advice",
)

class _RoutingLLMOutput(BaseModel):
    """Subset response generated by the routing LLM call."""

    model_config = ConfigDict(extra="forbid", str_strip_whitespace=True)

    confidence_level: ConfidenceLevel = Field(
        description="Routing confidence: high, medium, or low.",
    )
    ai_reasoning: str = Field(
        description="Brief explanation for routing and risk decisions.",
    )


class TattooRouter:
    """Apply routing and risk rules, then craft a staff-ready draft reply."""

    def __init__(
        self,
        llm: ChatOpenAI | None = None,
        model_name: str = "gpt-4o",
        reply_composer: ConversationReplyComposer | None = None,
    ) -> None:
        self._llm = llm or get_chat_model(model_name=model_name)
        self._parser = JsonOutputParser(pydantic_object=_RoutingLLMOutput)
        self._reply_composer = reply_composer or ConversationReplyComposer()

    def route(
        self,
        extracted: TattooExtractionDraft,
        current_message: str = "",
        recent_chat_history: list[Message] | None = None,
    ) -> AIExtractionOutput:
        """Create final output with a concise conversational reply."""
        suggested_artist = self._suggest_artist(
            style_tags=extracted.style_tags,
            size_estimate_cm=extracted.size_estimate_cm,
        )
        risk_level = self._classify_risk(extracted)
        llm_output = self._generate_reasoning_and_reply(
            extracted=extracted,
            suggested_artist=suggested_artist,
            risk_level=risk_level,
            current_message=current_message,
            recent_chat_history=recent_chat_history or [],
        )
        draft_reply = self._reply_composer.compose(
            extracted=extracted,
            current_message=current_message,
            recent_chat_history=recent_chat_history,
            risk_level=risk_level,
        )

        return AIExtractionOutput(
            tattoo_idea=extracted.tattoo_idea,
            style_tags=extracted.style_tags,
            placement=extracted.placement,
            size_estimate_cm=extracted.size_estimate_cm,
            color_preference=extracted.color_preference,
            suggested_artist=suggested_artist,
            confidence_level=llm_output.confidence_level,
            ai_reasoning=llm_output.ai_reasoning,
            missing_information=extracted.missing_information,
            risk_level=risk_level,
            draft_reply=draft_reply,
        )

    def _suggest_artist(
        self,
        style_tags: list[str],
        size_estimate_cm: str,
    ) -> SuggestedArtist:
        """Route artist using the required deterministic rules."""
        style_set = {tag.strip().lower() for tag in style_tags}
        has_nina_style = bool(style_set.intersection(_NINA_STYLE_TAGS))
        has_hoss_style = bool(style_set.intersection(_HOSS_STYLE_TAGS))

        if has_nina_style and not has_hoss_style:
            return "Nina"
        if has_hoss_style or self._is_large_scale(size_estimate_cm):
            return "Hoss"
        if has_nina_style:
            return "Nina"
        return "Unclear"

    def _is_large_scale(self, size_estimate_cm: str) -> bool:
        """Detect large-scale requests from numeric size hints or wording."""
        normalized = size_estimate_cm.lower()
        number_matches = re.findall(r"\d+(?:\.\d+)?", normalized)
        for item in number_matches:
            try:
                if float(item) >= 20.0:
                    return True
            except ValueError:
                continue

        size_words = ("sleeve", "full back", "back piece", "large", "full arm")
        return any(word in normalized for word in size_words)

    def _classify_risk(self, extracted: TattooExtractionDraft) -> RiskLevel:
        """Classify low vs high risk based on content and missing info."""
        searchable = " ".join(
            [
                extracted.tattoo_idea.lower(),
                extracted.placement.lower(),
                extracted.size_estimate_cm.lower(),
                extracted.color_preference.lower(),
            ]
        )

        # High-risk intent always takes precedence over intake completeness.
        if any(term in searchable for term in _HIGH_RISK_TERMS):
            return "high"

        # Standard missing intake fields are safe for conversational follow-up.
        missing = set(extracted.missing_information)
        if missing.issubset(_ALL_STANDARD_INTAKE_MISSING):
            return "low"

        # Fail closed if a future anomalous missing value bypasses validation.
        return "high"

    def _generate_reasoning_and_reply(
        self,
        extracted: TattooExtractionDraft,
        suggested_artist: SuggestedArtist,
        risk_level: RiskLevel,
        current_message: str,
        recent_chat_history: list[Message],
    ) -> _RoutingLLMOutput:
        """Generate internal reasoning without client-facing prose."""
        try:
            format_instructions = self._parser.get_format_instructions()
            human_prompt = build_routing_human_prompt(
                extracted_data=extracted.model_dump(),
                suggested_artist=suggested_artist,
                risk_level=risk_level,
                current_message=current_message,
                recent_chat_history=recent_chat_history,
                format_instructions=format_instructions,
            )
            response = self._llm.invoke(
                [
                    SystemMessage(content=ROUTING_SYSTEM_PROMPT),
                    HumanMessage(content=human_prompt),
                ]
            )
            parsed = self._parser.parse(self._coerce_content_to_text(response.content))
            return _RoutingLLMOutput.model_validate(parsed)
        except Exception as exc:  # pragma: no cover - defensive branch
            LOGGER.warning("Routing LLM fallback used: %s", exc)
            return self._fallback_llm_output(
                suggested_artist=suggested_artist,
                risk_level=risk_level,
            )

    def _fallback_llm_output(
        self,
        suggested_artist: SuggestedArtist,
        risk_level: RiskLevel,
    ) -> _RoutingLLMOutput:
        """Build deterministic output if the LLM call fails."""
        confidence_level: ConfidenceLevel
        if suggested_artist != "Unclear" and risk_level == "low":
            confidence_level = "high"
        elif suggested_artist == "Unclear":
            confidence_level = "low"
        else:
            confidence_level = "medium"

        ai_reasoning = (
            "Applied style and size routing rules, then checked risk keywords "
            "and missing fields for triage."
        )

        return _RoutingLLMOutput(
            confidence_level=confidence_level,
            ai_reasoning=ai_reasoning,
        )

    def _coerce_content_to_text(self, content: Any) -> str:
        """Normalize LangChain content payload to plain text."""
        if isinstance(content, str):
            return content
        if isinstance(content, list):
            text_parts: list[str] = []
            for item in content:
                if isinstance(item, dict):
                    text_value = item.get("text")
                    if isinstance(text_value, str):
                        text_parts.append(text_value)
            return "".join(text_parts)
        return str(content)
