"""Artist routing and risk classification module."""

from __future__ import annotations

import json
import logging
import re
from typing import Any

from langchain_core.messages import HumanMessage, SystemMessage
from langchain_core.output_parsers import JsonOutputParser
from langchain_openai import ChatOpenAI
from pydantic import BaseModel, ConfigDict, Field

from .llm import get_chat_model
from .schemas import AIExtractionOutput, TattooExtractionDraft

LOGGER = logging.getLogger(__name__)

_NINA_STYLE_TAGS = {"fine-line", "minimal", "micro-realism"}
_HOSS_STYLE_TAGS = {"watercolor", "traditional"}
_BASIC_LOW_RISK_MISSING = {"size in cm", "placement"}

_HIGH_RISK_TERMS = (
    "price",
    "pricing",
    "cost",
    "quote",
    "booking",
    "book an appointment",
    "complaint",
    "refund",
    "bad experience",
    "design this for me",
    "complex design advice",
)

_ROUTING_SYSTEM_PROMPT = (
    "You are a tattoo studio operations assistant. "
    "You will receive a rule-based artist suggestion and risk level. "
    "Do not change those values. Return valid JSON only with "
    "confidence_level, ai_reasoning, and draft_reply."
)


class _RoutingLLMOutput(BaseModel):
    """Subset response generated by the routing LLM call."""

    model_config = ConfigDict(extra="forbid", str_strip_whitespace=True)

    confidence_level: str = Field(
        description="Routing confidence: high, medium, or low.",
    )
    ai_reasoning: str = Field(
        description="Brief explanation for routing and risk decisions.",
    )
    draft_reply: str = Field(
        description="Polite client-facing response draft.",
    )


class TattooRouter:
    """Apply routing and risk rules, then craft a staff-ready draft reply."""

    def __init__(
        self,
        llm: ChatOpenAI | None = None,
        model_name: str = "gpt-4o",
    ) -> None:
        self._llm = llm or get_chat_model(model_name=model_name)
        self._parser = JsonOutputParser(pydantic_object=_RoutingLLMOutput)

    def route(self, extracted: TattooExtractionDraft) -> AIExtractionOutput:
        """Create final AIExtractionOutput from extracted intake information."""
        suggested_artist = self._suggest_artist(
            style_tags=extracted.style_tags,
            size_estimate_cm=extracted.size_estimate_cm,
        )
        risk_level = self._classify_risk(extracted)
        llm_output = self._generate_reasoning_and_reply(
            extracted=extracted,
            suggested_artist=suggested_artist,
            risk_level=risk_level,
        )

        confidence_level = self._normalize_confidence(llm_output.confidence_level)
        return AIExtractionOutput(
            tattoo_idea=extracted.tattoo_idea,
            style_tags=extracted.style_tags,
            placement=extracted.placement,
            size_estimate_cm=extracted.size_estimate_cm,
            color_preference=extracted.color_preference,
            suggested_artist=suggested_artist,
            confidence_level=confidence_level,
            ai_reasoning=llm_output.ai_reasoning,
            missing_information=extracted.missing_information,
            risk_level=risk_level,
            draft_reply=llm_output.draft_reply,
        )

    def _suggest_artist(
        self,
        style_tags: list[str],
        size_estimate_cm: str,
    ) -> str:
        """Route artist using the required deterministic rules."""
        style_set = {tag.strip().lower() for tag in style_tags}
        has_nina_style = bool(style_set.intersection(_NINA_STYLE_TAGS))
        has_hoss_style = bool(style_set.intersection(_HOSS_STYLE_TAGS))

        if has_nina_style and not has_hoss_style:
            return "Nina"
        if has_hoss_style or self._is_large_scale(size_estimate_cm):
            return "Hoss"
        if has_nina_style:
            return "Nina"
        return "Unclear"

    def _is_large_scale(self, size_estimate_cm: str) -> bool:
        """Detect large-scale requests from numeric size hints or wording."""
        normalized = size_estimate_cm.lower()
        number_matches = re.findall(r"\d+(?:\.\d+)?", normalized)
        for item in number_matches:
            try:
                if float(item) >= 20.0:
                    return True
            except ValueError:
                continue

        size_words = ("sleeve", "full back", "back piece", "large", "full arm")
        return any(word in normalized for word in size_words)

    def _classify_risk(self, extracted: TattooExtractionDraft) -> str:
        """Classify low vs high risk based on content and missing info."""
        searchable = " ".join(
            [
                extracted.tattoo_idea.lower(),
                extracted.placement.lower(),
                extracted.size_estimate_cm.lower(),
                extracted.color_preference.lower(),
            ]
        )

        if any(term in searchable for term in _HIGH_RISK_TERMS):
            return "high"

        missing = set(extracted.missing_information)
        if not missing or missing.issubset(_BASIC_LOW_RISK_MISSING):
            return "low"

        return "low"

    def _generate_reasoning_and_reply(
        self,
        extracted: TattooExtractionDraft,
        suggested_artist: str,
        risk_level: str,
    ) -> _RoutingLLMOutput:
        """Generate human-readable reasoning and draft reply in one LLM call."""
        try:
            format_instructions = self._parser.get_format_instructions()
            human_prompt = (
                "Use these fixed values exactly:\n"
                f"suggested_artist: {suggested_artist}\n"
                f"risk_level: {risk_level}\n\n"
                "Extracted data:\n"
                f"{json.dumps(extracted.model_dump(), ensure_ascii=True)}\n\n"
                "Return valid JSON only with fields:\n"
                "confidence_level, ai_reasoning, draft_reply.\n"
                "confidence_level must be one of: high, medium, low.\n"
                "Keep ai_reasoning concise and operational.\n"
                "Draft reply must be polite and actionable.\n\n"
                f"{format_instructions}"
            )
            response = self._llm.invoke(
                [
                    SystemMessage(content=_ROUTING_SYSTEM_PROMPT),
                    HumanMessage(content=human_prompt),
                ]
            )
            parsed = self._parser.parse(self._coerce_content_to_text(response.content))
            return _RoutingLLMOutput.model_validate(parsed)
        except Exception as exc:  # pragma: no cover - defensive branch
            LOGGER.warning("Routing LLM fallback used: %s", exc)
            return self._fallback_llm_output(
                extracted=extracted,
                suggested_artist=suggested_artist,
                risk_level=risk_level,
            )

    def _fallback_llm_output(
        self,
        extracted: TattooExtractionDraft,
        suggested_artist: str,
        risk_level: str,
    ) -> _RoutingLLMOutput:
        """Build deterministic output if the LLM call fails."""
        if suggested_artist != "Unclear" and risk_level == "low":
            confidence_level = "high"
        elif suggested_artist == "Unclear":
            confidence_level = "low"
        else:
            confidence_level = "medium"

        ai_reasoning = (
            "Applied style and size routing rules, then checked risk keywords "
            "and missing fields for triage."
        )

        if risk_level == "high":
            draft_reply = (
                "Thanks for your message. Your request needs a senior studio "
                "review before we proceed. Our team will follow up shortly with "
                "next steps and clear guidance."
            )
        else:
            if extracted.missing_information:
                missing = ", ".join(extracted.missing_information)
                draft_reply = (
                    "Thanks for your inquiry. To give you an accurate next step, "
                    f"please share: {missing}. Once we have that, we can continue "
                    "with artist matching and scheduling."
                )
            else:
                draft_reply = (
                    "Thanks for sharing the details. We have enough information "
                    "to continue and will follow up with artist availability and "
                    "recommended booking options."
                )

        return _RoutingLLMOutput(
            confidence_level=confidence_level,
            ai_reasoning=ai_reasoning,
            draft_reply=draft_reply,
        )

    def _normalize_confidence(self, value: str) -> str:
        """Normalize confidence to high, medium, or low."""
        normalized = value.strip().lower()
        if normalized in {"high", "medium", "low"}:
            return normalized
        return "medium"

    def _coerce_content_to_text(self, content: Any) -> str:
        """Normalize LangChain content payload to plain text."""
        if isinstance(content, str):
            return content
        if isinstance(content, list):
            text_parts: list[str] = []
            for item in content:
                if isinstance(item, dict):
                    text_value = item.get("text")
                    if isinstance(text_value, str):
                        text_parts.append(text_value)
            return "".join(text_parts)
        return str(content)
