"""Artist routing and risk classification module."""

from __future__ import annotations

import logging
from collections import Counter
from decimal import Decimal
from typing import TYPE_CHECKING, Any

from langchain_core.messages import HumanMessage, SystemMessage
from langchain_core.output_parsers import JsonOutputParser
from langchain_openai import ChatOpenAI
from pydantic import BaseModel, ConfigDict, Field, StrictStr

from .artist_config import ArtistConfigManager, ArtistProfile
from .cold_start import COLD_START_THRESHOLD, ColdStartManager
from .decision_schemas import DecisionHistoryExample
from .llm import get_chat_model
from .pricing import parse_size_cm
from .prompts import (
    DRAFT_REPLY_SYSTEM_PROMPT,
    ROUTING_SYSTEM_PROMPT,
    build_draft_reply_human_prompt,
    build_routing_human_prompt,
)
from .reply import ConversationReplyComposer
from .routing_rules import RoutingRule, RoutingRuleEngine
from .schemas import (
    AIExtractionOutput,
    ConfidenceLevel,
    Message,
    MessageSource,
    RiskLevel,
    SuggestedArtist,
    TattooExtractionDraft,
)

if TYPE_CHECKING:
    from .vector_store import VectorStoreManager

LOGGER = logging.getLogger(__name__)

_VECTOR_SEARCH_TOP_K = 12


class _RoutingLLMOutput(BaseModel):
    """Subset response generated by the routing LLM call."""

    model_config = ConfigDict(extra="forbid", str_strip_whitespace=True)

    confidence_level: ConfidenceLevel = Field(
        description="Routing confidence: high, medium, or low.",
    )
    ai_reasoning: str = Field(
        description="Brief explanation for routing and risk decisions.",
    )


class _DraftReplyLLMOutput(BaseModel):
    """Strict client-facing reply returned by the language model."""

    model_config = ConfigDict(extra="forbid", str_strip_whitespace=True)

    draft_reply: StrictStr = Field(min_length=1, max_length=2000)


class _ArtistRoutingDecision(BaseModel):
    """Validated artist result produced before risk and reply generation."""

    model_config = ConfigDict(extra="forbid", str_strip_whitespace=True)

    suggested_artist: SuggestedArtist
    confidence_level: ConfidenceLevel
    reasoning: str = Field(min_length=1, max_length=500)
    cold_start: bool = False


class TattooRouter:
    """Apply routing and risk rules, then craft a staff-ready draft reply."""

    def __init__(
        self,
        llm: ChatOpenAI | None = None,
        model_name: str = "gpt-4o",
        reply_composer: ConversationReplyComposer | None = None,
        artist_config_manager: ArtistConfigManager | None = None,
        vector_store: VectorStoreManager | None = None,
        cold_start_manager: ColdStartManager | None = None,
        routing_rule_engine: RoutingRuleEngine | None = None,
    ) -> None:
        """Initialize model, configuration, retrieval, and safety services."""
        self._llm = llm or get_chat_model(model_name=model_name)
        self._parser = JsonOutputParser(pydantic_object=_RoutingLLMOutput)
        self._draft_parser = JsonOutputParser(
            pydantic_object=_DraftReplyLLMOutput
        )
        self._reply_composer = reply_composer or ConversationReplyComposer()
        self._artist_config = (
            artist_config_manager
            if artist_config_manager is not None
            else ArtistConfigManager()
        )
        self._vector_store = vector_store
        self._cold_start_manager = (
            cold_start_manager
            if cold_start_manager is not None
            else ColdStartManager()
        )
        self._routing_rule_engine = (
            routing_rule_engine
            if routing_rule_engine is not None
            else RoutingRuleEngine()
        )

    def route(
        self,
        extracted: TattooExtractionDraft,
        current_message: str = "",
        recent_chat_history: list[Message] | None = None,
        existing_db_state: dict[str, Any] | None = None,
        message_source: MessageSource = "whatsapp",
    ) -> AIExtractionOutput:
        """Create final output with reply formatting for its source."""
        history = recent_chat_history or []
        db_state = existing_db_state or {}
        artist_decision = self._suggest_artist(extracted)
        risk_level = self._classify_risk(extracted)

        llm_output = self._routing_llm_output(
            artist_decision=artist_decision,
            extracted=extracted,
            risk_level=risk_level,
            current_message=current_message,
            recent_chat_history=history,
        )
        ai_reasoning = self._combine_routing_reasoning(
            artist_decision.reasoning,
            llm_output.ai_reasoning,
        )
        draft_reply = self._generate_draft_reply(
            extracted=extracted,
            current_message=current_message,
            recent_chat_history=history,
            suggested_artist=artist_decision.suggested_artist,
            risk_level=risk_level,
            existing_db_state=db_state,
            message_source=message_source,
        )

        return AIExtractionOutput(
            tattoo_idea=extracted.tattoo_idea,
            style_tags=extracted.style_tags,
            placement=extracted.placement,
            size_estimate_cm=extracted.size_estimate_cm,
            color_preference=extracted.color_preference,
            date=extracted.date,
            time=extracted.time,
            suggested_artist=artist_decision.suggested_artist,
            confidence_level=artist_decision.confidence_level,
            ai_reasoning=ai_reasoning,
            missing_information=extracted.missing_information,
            risk_level=risk_level,
            draft_reply=draft_reply,
            auto_reply_allowed=risk_level == "low",
            telegram_review_required=risk_level == "high",
        )

    def _generate_draft_reply(
        self,
        extracted: TattooExtractionDraft,
        current_message: str,
        recent_chat_history: list[Message],
        suggested_artist: SuggestedArtist,
        risk_level: RiskLevel,
        existing_db_state: dict[str, Any],
        message_source: MessageSource,
    ) -> str:
        """Generate and strictly validate a client-facing draft reply."""
        if message_source == "outlook":
            return self._reply_composer.compose_outlook_email(
                extracted=extracted,
                existing_db_state=existing_db_state,
            )

        try:
            format_instructions = self._draft_parser.get_format_instructions()
            human_prompt = build_draft_reply_human_prompt(
                current_message=current_message,
                extracted_details={
                    "tattoo_idea": extracted.tattoo_idea,
                    "style": list(extracted.style_tags),
                    "placement": extracted.placement,
                    "size": extracted.size_estimate_cm,
                    "color": extracted.color_preference,
                    "date": extracted.date,
                    "time": extracted.time,
                },
                missing_information=extracted.missing_information,
                recent_chat_history=recent_chat_history,
                suggested_artist=suggested_artist,
                risk_level=risk_level,
                format_instructions=format_instructions,
                existing_db_state=existing_db_state,
            )
            response = self._llm.invoke(
                [
                    SystemMessage(content=DRAFT_REPLY_SYSTEM_PROMPT),
                    HumanMessage(content=human_prompt),
                ]
            )
            parsed = self._draft_parser.parse(
                self._coerce_content_to_text(response.content)
            )
            output = _DraftReplyLLMOutput.model_validate(parsed)
            return output.draft_reply.strip()
        except Exception as exc:  # pragma: no cover - defensive branch
            LOGGER.warning("Draft reply LLM fallback used: %s", exc)
            return self._reply_composer.compose_validation(
                extracted=extracted,
                current_message=current_message,
                recent_chat_history=recent_chat_history,
                risk_level=risk_level,
            )

    def _suggest_artist(
        self,
        extracted: TattooExtractionDraft,
    ) -> _ArtistRoutingDecision:
        """Select an artist from cold start, configured rules, or history."""
        is_cold_start, record_count = self._cold_start_status()
        if is_cold_start:
            self._cold_start_manager.log_cold_start_warning()
            return _ArtistRoutingDecision(
                suggested_artist="Unclear",
                confidence_level="low",
                reasoning=self._cold_start_manager.build_status_message(
                    record_count
                ),
                cold_start=True,
            )

        rules = self._routing_rule_engine.evaluate(extracted)
        matches = self._search_similar_cases(extracted)
        rule_decision = self._suggest_from_rules(
            rules=rules,
            matches=matches,
            extracted=extracted,
        )
        if rule_decision is not None:
            return rule_decision
        if matches:
            return self._suggest_from_history(matches, extracted)
        return self._suggest_from_config(extracted)

    def _cold_start_status(self) -> tuple[bool, int]:
        """Return cold-start state and a safe collected-record count."""
        if self._vector_store is None:
            return True, 0
        record_count = self._cold_start_manager.get_record_count(
            self._vector_store
        )
        return record_count < COLD_START_THRESHOLD, record_count

    def _search_similar_cases(
        self,
        extracted: TattooExtractionDraft,
    ) -> list[tuple[float, DecisionHistoryExample]]:
        """Retrieve similar verified cases after cold start has ended."""
        if self._vector_store is None:
            return []
        try:
            return self._vector_store.search_similar_cases(
                self._build_vector_query(extracted),
                top_k=_VECTOR_SEARCH_TOP_K,
            )
        except Exception as exc:  # pragma: no cover - defensive branch
            LOGGER.warning("Artist vector search failed: %s", exc)
            return []

    def _build_vector_query(self, extracted: TattooExtractionDraft) -> str:
        """Render current features in the vector store's indexed format."""
        styles = ", ".join(extracted.style_tags) or "unknown"
        placement = extracted.placement or "unknown"
        size = extracted.size_estimate_cm or "unknown"
        color = extracted.color_preference or "unknown"
        return (
            f"Tattoo styles: {styles}. Placement: {placement}. "
            f"Size in centimeters: {size}. Color preference: {color}."
        )

    def _suggest_from_history(
        self,
        matches: list[tuple[float, DecisionHistoryExample]],
        extracted: TattooExtractionDraft,
    ) -> _ArtistRoutingDecision:
        """Choose the most frequent eligible artist in similar cases."""
        assignments: Counter[str] = Counter()
        seen_example_ids: set[str] = set()
        size_cm = parse_size_cm(extracted.size_estimate_cm)
        for _, example in matches:
            if example.example_id in seen_example_ids:
                continue
            seen_example_ids.add(example.example_id)
            artist_key = example.final_artist_key
            if (
                artist_key is not None
                and self._artist_config.validate_artist_assignment(
                    artist_key,
                    extracted.style_tags,
                )
            ):
                profile = self._artist_config.get_artist_by_key(artist_key)
                if (
                    profile is not None
                    and self._artist_accepts_size(profile, size_cm)
                ):
                    assignments[artist_key] += 1

        if not assignments:
            return self._manual_history_decision(
                "Similar cases contain no active artist assignments "
                "compatible with the detected style and size."
            )

        best_count = max(assignments.values())
        winners = [
            artist_key
            for artist_key, count in assignments.items()
            if count == best_count
        ]
        if len(winners) != 1:
            return self._manual_history_decision(
                "Similar cases produced an unresolved artist tie."
            )

        profile = self._artist_config.get_artist_by_key(winners[0])
        if profile is None or not profile.is_active:
            return self._manual_history_decision(
                "The historical artist is unavailable for assignment."
            )
        confidence: ConfidenceLevel = "medium"
        if best_count >= 2:
            confidence = "high"
        return _ArtistRoutingDecision(
            suggested_artist=profile.display_name,
            confidence_level=confidence,
            reasoning=(
                f"Suggested artist: {profile.display_name} based on "
                f"{best_count} similar historical cases."
            ),
        )

    def _manual_history_decision(
        self,
        reason: str,
    ) -> _ArtistRoutingDecision:
        """Return a safe unresolved result for unusable history."""
        return _ArtistRoutingDecision(
            suggested_artist="Unclear",
            confidence_level="low",
            reasoning=f"Manual artist assignment required. {reason}",
        )

    def _suggest_from_rules(
        self,
        rules: list[RoutingRule],
        matches: list[tuple[float, DecisionHistoryExample]],
        extracted: TattooExtractionDraft,
    ) -> _ArtistRoutingDecision | None:
        """Apply the highest-priority valid rule and add history support."""
        valid_rules = self._valid_artist_rules(rules, extracted)
        if not valid_rules:
            return None

        highest_priority = valid_rules[0].priority
        highest_rules = [
            rule for rule in valid_rules if rule.priority == highest_priority
        ]
        artist_keys = {rule.artist_key for rule in highest_rules}
        rule_names = self._rule_names(valid_rules)
        if len(artist_keys) != 1:
            return _ArtistRoutingDecision(
                suggested_artist="Unclear",
                confidence_level="low",
                reasoning=(
                    "Manual artist assignment required. Conflicting "
                    f"highest-priority rules matched. Applied routing rules: "
                    f"{rule_names}."
                ),
            )

        artist_key = next(iter(artist_keys))
        profile = self._artist_config.get_artist_by_key(artist_key)
        if profile is None or not profile.is_active:
            return None

        support_count = self._historical_artist_support(
            artist_key,
            matches,
        )
        confidence: ConfidenceLevel = "medium"
        if support_count >= 2:
            confidence = "high"
        reasoning = (
            f"Suggested artist: {profile.display_name} based on routing rule "
            f"'{highest_rules[0].name}' at priority {highest_priority}. "
            f"Applied routing rules: {rule_names}."
        )
        if support_count:
            reasoning = (
                f"{reasoning} Historical support: {support_count} similar "
                "cases assigned this artist."
            )
        return _ArtistRoutingDecision(
            suggested_artist=profile.display_name,
            confidence_level=confidence,
            reasoning=reasoning,
        )

    def _valid_artist_rules(
        self,
        rules: list[RoutingRule],
        extracted: TattooExtractionDraft,
    ) -> list[RoutingRule]:
        """Keep rules targeting active artists within configured size limits."""
        valid: list[RoutingRule] = []
        size_cm = parse_size_cm(extracted.size_estimate_cm)
        for rule in rules:
            profile = self._artist_config.get_artist_by_key(rule.artist_key)
            if (
                profile is None
                or not self._artist_config.validate_artist_assignment(
                    rule.artist_key,
                    extracted.style_tags,
                )
                or not self._artist_accepts_size(profile, size_cm)
            ):
                LOGGER.warning(
                    "Ignored routing rule %s for unavailable artist %s.",
                    rule.name,
                    rule.artist_key,
                )
                continue
            valid.append(rule)
        return valid

    def _historical_artist_support(
        self,
        artist_key: str,
        matches: list[tuple[float, DecisionHistoryExample]],
    ) -> int:
        """Count unique similar cases supporting one artist assignment."""
        return len(
            {
                example.example_id
                for _, example in matches
                if example.final_artist_key == artist_key
            }
        )

    def _rule_names(self, rules: list[RoutingRule]) -> str:
        """Return a bounded audit label for matching routing rules."""
        names = ", ".join(rule.name for rule in rules[:5])
        if len(rules) > 5:
            names = f"{names}, and {len(rules) - 5} more"
        if len(names) > 220:
            return f"{names[:217]}..."
        return names

    def _suggest_from_config(
        self,
        extracted: TattooExtractionDraft,
    ) -> _ArtistRoutingDecision:
        """Use active artist specialties only when history has no matches."""
        style_tags = set(extracted.style_tags).difference({"unknown"})
        size_cm = parse_size_cm(extracted.size_estimate_cm)
        ranked: list[tuple[int, ArtistProfile]] = []
        for artist in self._artist_config.get_active_artists():
            if not self._artist_accepts_size(artist, size_cm):
                continue
            overlap = style_tags.intersection(artist.specialties)
            if overlap:
                ranked.append((len(overlap), artist))

        if not ranked:
            return _ArtistRoutingDecision(
                suggested_artist="Unclear",
                confidence_level="low",
                reasoning=(
                    "No unique active artist matched configured specialties "
                    "and size limits."
                ),
            )

        best_score = max(score for score, _ in ranked)
        winners = [artist for score, artist in ranked if score == best_score]
        if len(winners) != 1:
            return _ArtistRoutingDecision(
                suggested_artist="Unclear",
                confidence_level="low",
                reasoning=(
                    "Configured specialties produced an unresolved artist tie."
                ),
            )

        winner = winners[0]
        return _ArtistRoutingDecision(
            suggested_artist=winner.display_name,
            confidence_level="medium",
            reasoning=(
                f"Suggested artist: {winner.display_name} based on configured "
                "specialties and size limits."
            ),
        )

    def _artist_accepts_size(
        self,
        artist: ArtistProfile,
        size_cm: Decimal | None,
    ) -> bool:
        """Return whether a known size falls inside an artist's limits."""
        if size_cm is None:
            return True
        if (
            artist.min_size_cm is not None
            and size_cm < Decimal(str(artist.min_size_cm))
        ):
            return False
        if (
            artist.max_size_cm is not None
            and size_cm > Decimal(str(artist.max_size_cm))
        ):
            return False
        return True

    def _classify_risk(
        self,
        extracted: TattooExtractionDraft,
    ) -> RiskLevel:
        """Classify only complete intakes as high risk for staff review."""
        return "high" if not extracted.missing_information else "low"

    def _routing_llm_output(
        self,
        artist_decision: _ArtistRoutingDecision,
        extracted: TattooExtractionDraft,
        risk_level: RiskLevel,
        current_message: str,
        recent_chat_history: list[Message],
    ) -> _RoutingLLMOutput:
        """Skip routing LLM work during cold start and call it otherwise."""
        if artist_decision.cold_start:
            return _RoutingLLMOutput(
                confidence_level="low",
                ai_reasoning=artist_decision.reasoning,
            )
        return self._generate_reasoning_and_reply(
            extracted=extracted,
            suggested_artist=artist_decision.suggested_artist,
            risk_level=risk_level,
            current_message=current_message,
            recent_chat_history=recent_chat_history,
        )

    def _combine_routing_reasoning(
        self,
        artist_reasoning: str,
        llm_reasoning: str,
    ) -> str:
        """Keep explicit artist evidence before supplemental risk reasoning."""
        if artist_reasoning.casefold() == llm_reasoning.casefold():
            return artist_reasoning
        return f"{artist_reasoning} {llm_reasoning}"

    def _generate_reasoning_and_reply(
        self,
        extracted: TattooExtractionDraft,
        suggested_artist: SuggestedArtist,
        risk_level: RiskLevel,
        current_message: str,
        recent_chat_history: list[Message],
    ) -> _RoutingLLMOutput:
        """Generate internal reasoning without client-facing prose."""
        try:
            format_instructions = self._parser.get_format_instructions()
            human_prompt = build_routing_human_prompt(
                extracted_data=extracted.model_dump(),
                suggested_artist=suggested_artist,
                risk_level=risk_level,
                current_message=current_message,
                recent_chat_history=recent_chat_history,
                format_instructions=format_instructions,
            )
            response = self._llm.invoke(
                [
                    SystemMessage(content=ROUTING_SYSTEM_PROMPT),
                    HumanMessage(content=human_prompt),
                ]
            )
            parsed = self._parser.parse(self._coerce_content_to_text(response.content))
            return _RoutingLLMOutput.model_validate(parsed)
        except Exception as exc:  # pragma: no cover - defensive branch
            LOGGER.warning("Routing LLM fallback used: %s", exc)
            return self._fallback_llm_output(
                suggested_artist=suggested_artist,
                risk_level=risk_level,
            )

    def _fallback_llm_output(
        self,
        suggested_artist: SuggestedArtist,
        risk_level: RiskLevel,
    ) -> _RoutingLLMOutput:
        """Build deterministic output if the LLM call fails."""
        confidence_level: ConfidenceLevel
        if suggested_artist != "Unclear" and risk_level == "low":
            confidence_level = "high"
        elif suggested_artist == "Unclear":
            confidence_level = "low"
        else:
            confidence_level = "medium"

        ai_reasoning = (
            "Applied style and size routing rules, then checked risk keywords "
            "and missing fields for triage."
        )

        return _RoutingLLMOutput(
            confidence_level=confidence_level,
            ai_reasoning=ai_reasoning,
        )

    def _coerce_content_to_text(self, content: Any) -> str:
        """Normalize LangChain content payload to plain text."""
        if isinstance(content, str):
            return content
        if isinstance(content, list):
            text_parts: list[str] = []
            for item in content:
                if isinstance(item, dict):
                    text_value = item.get("text")
                    if isinstance(text_value, str):
                        text_parts.append(text_value)
            return "".join(text_parts)
        return str(content)
